CREATE TABLE address (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    country VARCHAR(25) NOT NULL,
    city VARCHAR(25) NOT NULL,
    street VARCHAR(25) NOT NULL,
    UNIQUE(country, city, street)
);

CREATE TABLE images (
   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
   image bytea NOT NULL
);

CREATE TABLE supplier (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(25) NOT NULL,
    address_id BIGINT NOT NULL REFERENCES address(id),
    phone_number VARCHAR(25) NOT NULL
);

CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    client_name VARCHAR(25) NOT NULL,
    client_surname VARCHAR(25) NOT NULL,
    birthday DATE NOT NULL,
    gender VARCHAR(25) NOT NULL,
    registration_date DATE NOT NULL,
    address_id BIGINT NOT NULL REFERENCES address(id)
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(100) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    available_stock BIGINT NOT NULL,
    last_update_date DATE NOT NULL,
    supplier_id BIGINT NOT NULL REFERENCES supplier(id) ON DELETE CASCADE,
    image_id UUID REFERENCES images(id) ON DELETE SET NULL
);


